version: "3"

services:
  db:
    image: postgres:10.5-alpine
    volumes:
      - ./db-data:/var/lib/postgresql/data

  miner1:
    image: akropolisio/geth-miner
    build: .
    ports:
      - "8540:8540"
      - "30300:30300"
    volumes:
      - ./miner1-data:/data/eth

  miner2:
    image: akropolisio/geth-miner
    build: .
    ports:
      - "8540:8540"
      - "30300:30300"
    volumes:
      - ./miner2-data:/data/eth

  blockpipe:
    image: akropolisio/blockpipe:latest
    restart: always
    depends_on:
      - db
      - miner
    environment:
      - RUST_BACKTRACE=1
      - PG_PATH=postgres://bp_writer:password@db/blockpipe
      - RPC_PATH=http://miner1:8540/
