version: "3"

services:
  db:
    image: postgres:10.5-alpine
    volumes:
      - ./db-data:/var/lib/postgresql/data

  miner:
    image: akropolisio/geth-miner
    build: .
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - ./miner-data:/data/eth

  blockpipe:
    image: akropolisio/blockpipe:latest
    restart: always
    depends_on:
      - db
      - miner
    environment:
      - RUST_BACKTRACE=1
      - PG_PATH=postgres://bp_writer:password@db/blockpipe
      - RPC_PATH=http://miner:8545/
