version: "3"

services:
  db:
    image: postgres:10.5-alpine
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - back

  miner:
    image: akropolisio/geth-miner
    build: .
    networks:
      - eth
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - ./miner-data:/data/eth

  blockpipe:
    image: akropolisio/blockpipe:latest
    depends_on:
      - db
      - miner
    networks:
      - back
      - eth
    environment:
      - RUST_BACKTRACE=1
      - PG_PATH=postgres://bp_writer:password@db/blockpipe
      - RPC_PATH=http://miner:8545/

networks:
  back:
    driver: bridge
  eth:
    driver: bridge
